# Generated by Django 5.2.2 on 2025-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the query.', max_length=100)),
                ('contact_email', models.EmailField(help_text='Email address for contact.', max_length=254)),
                ('institution_name', models.CharField(blank=True, help_text='Name of the institution (optional).', max_length=200, null=True)),
                ('message', models.TextField(help_text='The general query or message submitted.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the query was submitted.')),
            ],
            options={
                'verbose_name_plural': 'General Queries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the query.', max_length=100)),
                ('organisation', models.CharField(blank=True, help_text='Name of the organization (optional).', max_length=200, null=True)),
                ('contact_email', models.EmailField(help_text='Email address for contact.', max_length=254)),
                ('message', models.TextField(help_text='The query or message submitted.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the query was submitted.')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sponsoring organization.', max_length=200)),
                ('tier', models.CharField(choices=[('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', help_text='Sponsorship tier (e.g., Gold, Platinum, Silver).', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
                'ordering': ['tier'],
            },
        ),
    ]
