# Generated by Django 5.2.2 on 2025-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='mobile_number',
            field=models.TextField(default=1212121212, help_text='Mobile number for contact.', max_length=10),
            preserve_default=False,
        ),
    ]
