# Generated by Django 5.2.2 on 2025-06-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('valid_till', models.DateField()),
                ('schedule_for_later', models.DateField(help_text='Schedule time')),
                ('manual_visibility', models.BooleanField(blank=True, help_text='Set visibility manually', null=True)),
                ('manual_validity', models.BooleanField(blank=True, help_text='Set validity manually', null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('validity', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
