# Generated by Django 5.2.2 on 2025-06-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcments',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REGISTERED', 'Registered'), ('NOT_REGISTERED', 'Not Registered')], default='GENERAL', max_length=20),
        ),
    ]
