# Generated by Django 5.2.2 on 2025-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0002_announcments_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcments',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REGISTERED', 'Registered'), ('NOT_REGISTERED', 'Not Registered')], max_length=20),
        ),
    ]
