# Generated by Django 5.2.2 on 2025-06-12 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0003_alter_announcments_category'),
        ('team_profile', '0003_rename_member_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('accepting_response', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField()),
                ('schedule_at', models.DateTimeField()),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_profile.team')),
            ],
        ),
    ]
