# Generated by Django 5.2.2 on 2025-06-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0004_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='team_name',
            new_name='team',
        ),
    ]
