# Generated by Django 5.2.2 on 2025-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0005_rename_team_name_submission_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
