# Generated by Django 5.2.2 on 2025-06-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_home', '0006_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
