# Generated by Django 5.1.7 on 2025-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
