# Generated by Django 5.1.7 on 2025-05-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0002_team_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
