# Generated by Django 5.1.7 on 2025-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_profile', '0003_rename_member_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
