# Generated by Django 5.1.7 on 2025-06-04 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='ticket',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
