# Generated by Django 5.1.7 on 2025-06-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_query_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='response',
            field=models.TextField(default='contact us'),
            preserve_default=False,
        ),
    ]
