# Generated by Django 5.2.2 on 2025-06-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_query_responded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
