# Generated by Django 5.1.7 on 2025-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(default='Unknown College', max_length=100),
            preserve_default=False,
        ),
    ]
