# Generated by Django 5.2.2 on 2025-06-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_firstname_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='event_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_state',
            field=models.CharField(choices=[('Archived', 'archived'), ('Active', 'active')], default='active', max_length=10),
        ),
    ]
